/* Generated By:JavaCC: Do not edit this line. TiraTeimaParserConstants.java */
package tirateima.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TiraTeimaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int DIGITS = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int LETTERDIGIT = 10;
  /** RegularExpression Id. */
  int SCAPE_SEQUENCE = 11;
  /** RegularExpression Id. */
  int KW_LINE = 12;
  /** RegularExpression Id. */
  int KW_RECORD = 13;
  /** RegularExpression Id. */
  int KW_INT = 14;
  /** RegularExpression Id. */
  int KW_REAL = 15;
  /** RegularExpression Id. */
  int KW_CHAR = 16;
  /** RegularExpression Id. */
  int KW_STRING = 17;
  /** RegularExpression Id. */
  int KW_BOOLEAN = 18;
  /** RegularExpression Id. */
  int KW_VOID = 19;
  /** RegularExpression Id. */
  int KW_TEXT = 20;
  /** RegularExpression Id. */
  int KW_WRITE = 21;
  /** RegularExpression Id. */
  int KW_WRITELN = 22;
  /** RegularExpression Id. */
  int KW_COMMENT = 23;
  /** RegularExpression Id. */
  int KW_SOUND = 24;
  /** RegularExpression Id. */
  int KW_ASSIGN = 25;
  /** RegularExpression Id. */
  int KW_REWRITE = 26;
  /** RegularExpression Id. */
  int KW_RESET = 27;
  /** RegularExpression Id. */
  int KW_READ = 28;
  /** RegularExpression Id. */
  int KW_READLN = 29;
  /** RegularExpression Id. */
  int KW_CLOSE = 30;
  /** RegularExpression Id. */
  int KW_FUNCTION = 31;
  /** RegularExpression Id. */
  int KW_START = 32;
  /** RegularExpression Id. */
  int KW_END = 33;
  /** RegularExpression Id. */
  int KW_TRUE = 34;
  /** RegularExpression Id. */
  int KW_FALSE = 35;
  /** RegularExpression Id. */
  int KW_COLOR = 36;
  /** RegularExpression Id. */
  int KW_COLOR_INSIDE = 37;
  /** RegularExpression Id. */
  int KW_DIMENSION = 38;
  /** RegularExpression Id. */
  int KW_POSITION = 39;
  /** RegularExpression Id. */
  int INT_NUMBER = 40;
  /** RegularExpression Id. */
  int IDENTIFIER = 41;
  /** RegularExpression Id. */
  int FLOAT_NUMBER = 42;
  /** RegularExpression Id. */
  int STRING_LITERAL = 43;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 44;
  /** RegularExpression Id. */
  int OPEN_BRACE = 45;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 46;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 47;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 48;
  /** RegularExpression Id. */
  int OPEN_PAR = 49;
  /** RegularExpression Id. */
  int CLOSE_PAR = 50;
  /** RegularExpression Id. */
  int DOT = 51;
  /** RegularExpression Id. */
  int COMMA = 52;
  /** RegularExpression Id. */
  int COLON = 53;
  /** RegularExpression Id. */
  int SEMICOLON = 54;
  /** RegularExpression Id. */
  int ATTRIBUTION = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT>",
    "<DIGIT>",
    "<DIGITS>",
    "<LETTER>",
    "<LETTERDIGIT>",
    "<SCAPE_SEQUENCE>",
    "\"line\"",
    "\"record\"",
    "\"int\"",
    "\"real\"",
    "\"char\"",
    "\"string\"",
    "\"boolean\"",
    "\"void\"",
    "\"text\"",
    "\"write\"",
    "\"writeln\"",
    "\"comenta\"",
    "\"som\"",
    "\"assign\"",
    "\"rewrite\"",
    "\"reset\"",
    "\"read\"",
    "\"readln\"",
    "\"close\"",
    "\"function\"",
    "\"start\"",
    "\"end\"",
    "\"true\"",
    "\"false\"",
    "\"cor\"",
    "\"corexterna\"",
    "\"tamanho\"",
    "\"posicao\"",
    "<INT_NUMBER>",
    "<IDENTIFIER>",
    "<FLOAT_NUMBER>",
    "<STRING_LITERAL>",
    "<CHAR_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"=\"",
  };

}
